### ISSUE TITLE
Guzzle 6.0

### ISSUE THREAD

**Issue by vinkla** [99designs/http-signatures-guzzlehttp#5]
Any chance we can get this up to date with Guzzle 6.0?

**Comment by pda** [comment]
ping @navitronic

**Comment by navitronic** [comment]
This definitely seems like something that should happen

I'll take a look into this in the next week or so.

**Comment by vinkla** [comment]
:+1:

**Comment by vinkla** [comment]
@pda @navitronic I've done some research and I guess we should create a middleware to make it work with Guzzle 6.0? http://guzzle.readthedocs.org/en/latest/handlers-and-middleware.html

**Comment by vinkla** [comment]
@pda @navitronic I've done some research and I guess we should create a middleware to make it work with Guzzle 6.0? http://guzzle.readthedocs.org/en/latest/handlers-and-middleware.html

What can I do to help speed up this process?

**Comment by vinkla** [comment]
@pda @navitronic I've done some research and I guess we should [create a middleware](http://guzzle.readthedocs.org/en/latest/handlers-and-middleware.html) to make it work with Guzzle 6.0? What can I do to help speed things up?

**Comment by navitronic** [comment]
@vinkla I did some research on getting this implemented and the middleware approach seems to be the way to go. I haven't quite had the time to get the code written though. Happy to review anything you might want to do.

Not sure whether to aim to release a new `2.0` release and only support Guzzle 6+ or implement support alongside older Guzzle versions. I seem to remember seeing a few libraries taking the latter approach.

**Comment by vinkla** [comment]
IMO we shouldn't care about older versions of Guzzle and since we already have tagged releases developers could just use older versions of this package anyway. 

I tried making a custom middleware but don't know how we're going to sign the requests. The current `sign` method doesn't return the request back and the middlewares requires that. Any ideas how we can go about this?

**Comment by vinkla** [comment]
I've started working on support in #7, please take a look.

**Comment by pda** [comment]
> we shouldn't care about older versions of Guzzle and since we already have tagged releases developers could just use older versions of this package anyway.

I agree in general, but it depends if Guzzle 6 is something most of the community is likely to rapidly upgrade to. Otherwise there's inevitably demand for backported fixes etc. @navitronic are 99designs apps likely to be on Guzzle 6 already/soon?

**Comment by vinkla** [comment]
What I mean is that this package already supports the older versions. The older versions aren't likely to change in behaviour. So is there really a need to keep maintaining support for multiple versions when we already have support in old releases?

**Comment by pda** [comment]
Only if bugs or security issues are found in those old releases, and for some reason users of it can't/won't upgrade to Guzzle 6. But generally I'm all for dropping support for old versions, and bumping our major version accordingly.

**Comment by vinkla** [comment]
Sounds good :+1:

**Comment by navitronic** [comment]
@pda I don't think that we'll be going Guzzle 6 very soon. 

I was thinking about making the effort to try and eliminate Guzzle 3 from our stack and try and improve the general Guzzle 4+ (aka `guzzlehttp`) support of stuff we use. Could be quite a long process though.

**Comment by vinkla** [comment]
This issue is fairly old, closing it due to inactivity.

**Comment by rubensayshi** [comment]
@vinkla let's get my PR merged then ;)
